backend:
  name: github
  repo: MARKETProtocol/website
  branch: develop # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/blogPosts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter.
            # Remove any that aren't needed for posts
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Development", "The Team", "Crash Courses"]}
      - {label: "Published", name: "published_at", widget: "datetime"}
      - {label: "Read on Medium", name: "medium_link", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
